# This is a basic workflow to help you get started with Actions

name: BUILD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Install iverilog
      run: sudo apt install iverilog
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - run: python -m pip install numpy
    - name: Download workflow run artifacts
      uses: actions/download-artifact@v4
      with:
        name: arithmetic-circuits-8
        path: test_circuits        
    - name: Listing
      run: |
        ls
    - name: Run maji gate test
      run: |
        cd tests
        python3 test_maji.py
        cd ..
    - name: Run Basic gates test
      run: |
        cd tests
        python3 test_maji_gates.py
        cd ..
    - name: Run 8b Adders test
      run: |
        cd tests
        python3 test_maji_sadder.py
        python3 test_maji_uadder.py
        cd ..
    - name: Run 8b Muls test
      run: |
        cd tests
        python3 test_maji_smul.py
        python3 test_maji_umul.py
        cd ..